version: '3'
services:
    postgres:
      container_name: postgres
      ports:
        - "5432:5432"
      image: library/postgres:10.13
      restart: unless-stopped

      environment:
        - "LC_ALL=C.UTF-8"
        - POSTGRES_DB=${POSTGRES_DB}
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_PORT=${POSTGRES_PORT}
      volumes:
        - ./data/database-data:/var/lib/postgresql/data/ # persist data even if container shuts down

    solr:
      image: ekoindarto/solr-cvm:latest
      container_name: solr
      privileged: true
      ports:
        - "8983:8983"
      environment:
        - "SOLR_HOST=solr"
        - "SOLR_PORT=8983"
        - "SOLR_JAVA_MEM=-Xms1g -Xmx1g"
      volumes:
        - ./data/solr-data:/opt/solr/server/solr/collection1/data

    dataverse:
      image: ekoindarto/dataverse-cvm:5.3
      container_name: dataverse
      privileged: true
      ports:
        - "443:443"
        - "4848:4848"
        - "8085:8080"
      environment:
        - "CVM_SERVER_URL=https://vocabularies-dev.cessda.eu/v2/search/vocabularies"
        - "CVM_VOCAB_LANG=${CVM_VOCAB_LANG}" # Optional
        - "CVM_TSV_SOURCE=https://github.com/IQSS/dataverse-docker/releases/download/5.2-cv/citation.tsv"
        - "WAR_FILE=http://repo/dataverse.war"
#        - "GIT_SOURCE=https://github.com/ekoi/traefik-speeltuin"
#        - "GIT_BRANCH=v5.3-speeltuin"
        - "GIT_SOURCE=https://github.com/vicding-mi/dataverse"
        - "GIT_BRANCH=signposting-5.3"
        - "HOST_DNS_ADDRESS=0.0.0.0"
        - "LANG=en"
        - "BUNDLEPROPERTIES=Bundle.properties"
        - "ADMIN_EMAIL=admin@localhost"
        - "MAIL_SERVER=mailrelay"
        - "POSTGRES_SERVER=postgres"
        - "POSTGRES_PORT=5432"
        - "POSTGRES_DATABASE=dvndb"
        - "POSTGRES_USER=dvnuser"
        - "PGPASSWORD=dvnsecret"
        - "SOLR_LOCATION=solr:8983"
        - "TWORAVENS_LOCATION=NOT INSTALLED"
        - "RSERVE_HOST=localhost"
        - "RSERVE_PORT=6311"
        - "RSERVE_USER=rserve"
        - "RSERVE_PASSWORD=rserve"
        - "JVM_OPTS='-Xmx1g -Xms1g -XX:MaxPermSize=2g -XX:PermSize=2g'"
        - "DB_NAME=dvndb"
        - "DB_PORT=5432"
        - "DB_HOST=postgres"
        - "DB_USER=dvnuser"
      depends_on:
        - postgres
        - solr
      volumes:
        - ./data/dataverse-data:/usr/local/payara5/glassfish/domains/domain1/autodeploy
        - ~/.m2:/opt/payara/.m2

    repo:
      image: nginx:latest
      container_name: repo
      ports:
        - "8080:80"
      volumes:
        - ${LOCAL_WAR}:/usr/share/nginx/html/dataverse.war

    dbgui:
      image: dockage/phppgadmin
      container_name: dbgui
      environment:
        - PHP_PG_ADMIN_SERVER_HOST=postgres
      ports:
        - 8086:80

networks:
  dvn:
    driver: bridge

